apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: giropops-senhas
  namespace: argocd
spec:
  project: default
  source:
    helm: {}
    repoURL: 'https://github.com/carlosrovaris/argocd-apps.git'
    targetRevision: main
    path: giropops-senhas/helm
  destination:
    namespace: giropops
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      selfHeal: true ## Se houver alteracões no cluster, ele corrige automaticamente, torna o repositorio a fonte da verdade
    syncOptions:
      - CreateNamespace=true