global:
  domain: argocd-spoke.cluster.io

server:
  ingress:
    enabled: true
    ingressClassName: nginx
  extraArgs:
    - --insecure
  extensions:
    enabled: true
    image:
      repository: "quay.io/argoprojlabs/argocd-extension-installer"
    extensionList:
      - name: rollout-extension
        env:
          - name: EXTENSION_URL
            value: "https://github.com/argoproj-labs/rollout-extension/releases/download/v0.3.6/extension.tar"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: prometheus
      additionalLabels:
        release: prometheus

repoServer:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: prometheus
      additionalLabels:
        release: prometheus

configs:
  params:
    server.enable.proxy.extension: true
    ## Enable GitHub SSO
    ## server.dex.enable: true
    # dexserver.disable.tls: true
    # server.dex.server.strict.tls: true
    # dexserver.config: |
    #   connectors:
    #   - type: github
    #     id: github
    #     name: GitHub
    #     config:
    #       clientID: <clientID>
    #       clientSecret: <clientSecret>
    #       redirectURI: https://argocd.cluster.io/auth/callback
    #       orgs:
    #       - name: rovaris

dex:
  enabled: false

controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: prometheus
      additionalLabels:
        release: prometheus
    rules:
      enabled: true
      namespace: prometheus
      additionalLabels:
        release: prometheus
      spec:
      - alert: ArgoAppMissing
        expr: |
          absent(argocd_app_info) == 1
        for: 15m
        labels:
          severity: critical
        annotations:
          summary: "[Argo CD] No reported applications"
          description: >
            Argo CD has not reported any applications data for the past 15 minutes which
            means that it must be down or not functioning properly.  This needs to be
            resolved for this cloud to continue to maintain state.
      - alert: ArgoAppNotSynced
        expr: |
          argocd_app_info{sync_status!="Synced"} == 1
        for: 12h
        labels:
          severity: warning
        annotations:
          summary: "[{{`{{$labels.name}}`}}] Application not synchronized"
          description: >
            The application [{{`{{$labels.name}}`}} has not been synchronized for over
            12 hours which means that the state of this cloud has drifted away from the
            state inside Git.

notifications:
  telegram:
    enabled: true
    chatID: "123456789"
    token: "123456789:ABCDEF"
  notifier:
    enabled: true
    telegram:
      enabled: true
      chatID: "123456789"
      token: "123456789:ABCDEF"
