{{ if .Values.argocd.promtail.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://grafana.github.io/helm-charts'
    chart: promtail
    targetRevision: 6.17.0
    helm:
      valueFiles:
      - $values/infra-core/helm/promtail/values.yml
  - repoURL: 'https://github.com/carlosrovaris/argocd-idp.git'
    targetRevision: main
    ref: values
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  destination:
    namespace: logs
    server: https://kubernetes.default.svc
{{ end }}